# Generated by Django 4.0.4 on 2022-05-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='numer',
            new_name='number',
        ),
    ]
